Test/186502/unit tests
DFE-Digital/education-benchmarking-and-insights pull request #21
Opened 2023-12-06 15:30 UTC by spicy-rice

- Recreated react app using vite
- inc Typescript 
- Jest unit tests

2023-12-06 23:27 UTC, jrabbott commented
Please could we review and clean-up the folder structure with the front-end-components dir.

We seem to have front-end & frontend, several src, etc.

2023-12-07 11:03 UTC, joekadi requested changes
folder reorg

2023-12-07 11:07 UTC, joekadi submitted a review, later dismissed

2023-12-07 19:32 UTC, jrabbott requested changes
Please could we review and clean-up the folder structure with the front-end-components dir.

We seem to have front-end & frontend, several src, etc.

2023-12-08 11:56 UTC, jrabbott commented on front-end-components/src/App.test.tsx
With *.test,tsx do we have any preferences to whether they are placed with the *.tsx file in the src directory? or whether we place them in the tests directory?

2023-12-08 14:26 UTC, jrabbott commented on front-end-components/src/App.test.tsx
Lets stick with that for now then. We can always change it in future if it comes challenging.

2023-12-08 14:26 UTC, jrabbott approved these changes

2023-12-08 14:26 UTC, merged