Feature/185789/a11y automation
DFE-Digital/education-benchmarking-and-insights pull request #22
Opened 2023-12-07 11:13 UTC by Faizi52996

- BDD project for accessibility testing using Deque.Axecore.Playwright
-

2023-12-07 12:38 UTC, Faizi52996 commented
> Do we have some documentation for approach to accessibility testing? as well as developer documentation for running the tests locally?

I will be updating the Test Approach in a separate branch along with developer documentation as for some reasons i can not see the documentation folder in my rider currently.

2023-12-07 14:45 UTC, jrabbott requested changes

2023-12-07 19:42 UTC, jrabbott requested changes

2023-12-08 12:38 UTC, jrabbott commented on web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
> +        <PackageReference Include="nunit" Version="3.13.2"/>
Please can we keep them consistent rather than swapping. It will reduce the cognitive load on the team and keep things simple

2023-12-08 12:38 UTC, jrabbott commented on web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
> -        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
Please can you add it back. Thanks

2023-12-08 12:39 UTC, Faizi52996 commented on web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
> -        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
shouldn't it be EducationBenchmarking.Web.A11yTests as of the project name?

2023-12-08 12:41 UTC, jrabbott commented on web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
> -        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
I'm not referring to `RootNamespace` - that should be deleted,

`RestorePackagesWithLockFile` needs to be added back,

2023-12-08 12:45 UTC, Faizi52996 commented on web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
> -        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
added it back now.

2023-12-08 13:05 UTC, Faizi52996 commented on web/tests/EducationBenchmarking.Web.A11yTests/EducationBenchmarking.Web.A11yTests.csproj
> +        <PackageReference Include="nunit" Version="3.13.2"/>
replaced it with xunit.

2023-12-08 13:40 UTC, jrabbott approved these changes

2023-12-08 13:40 UTC, merged