Create Establishment-Level Expenditure Page
DFE-Digital/education-benchmarking-and-insights pull request #33
Opened 2023-12-13 12:18 UTC by J05h-L

WiP

[Ticket](https://dfe-ssp.visualstudio.com/s198-DfE-Benchmarking-service/_workitems/edit/187923)

basic layout for expenditure page created
controller added for this page for the following route ~/school-expenditure/{id}
id passed as a parameter to the method but not yet used
view model created taking SchoolName and LastFinancialYear - currently hardcoded values being passed by the controller
view created for the non react elements of the page.
some integration tests added using AngleSharp and Xunit

2023-12-13 15:48 UTC, michael-fielding requested changes

2023-12-13 15:58 UTC, J05h-L commented on web/src/EducationBenchmarking.Web/Controllers/SchoolExpenditureController.cs
> +            public IActionResult Details(string id)
corrected

2023-12-15 15:54 UTC, jrabbott commented on web/src/EducationBenchmarking.Web/Controllers/SchoolExpenditureController.cs
> +            public IActionResult Details(string id)
Fixed

2023-12-15 15:55 UTC, jrabbott approved these changes

2023-12-15 16:44 UTC, michael-fielding approved these changes

2023-12-15 16:53 UTC, merged