doc explaining how to integrate with dfe sign in
DFE-Digital/education-benchmarking-and-insights pull request #6
Opened 2023-11-23 14:32 UTC by joekadi

2023-11-24 16:37 UTC, michael-fielding commented
Can you convert this to a markdown doc in keeping with the rest of our documentation. You can use Mermaid for the diagrams

2023-11-24 16:38 UTC, michael-fielding requested changes
Can you convert this to a markdown doc in keeping with the rest of our documentation. You can use Mermaid for the diagrams

2023-11-29 10:48 UTC, joekadi commented
> Can you convert this to a markdown doc in keeping with the rest of our documentation. You can use Mermaid for the diagrams

done!

2023-11-29 10:51 UTC, michael-fielding approved these changes

2023-11-29 10:52 UTC, merged