adds local authority commercial resources page
DFE-Digital/education-benchmarking-and-insights pull request #686
Opened 2024-05-02 09:05 UTC by J05h-L

### Context
AB#199506 - AB#203890

### Change proposed in this pull request
Adds model, view and controller for this page.

### Guidance to review 
View model is currently unused. Controller currently just returns the view without any local authority data. Due to this EstablishmentHeading also is missing from the view. I propose if there are no objections that these are all picked up as tech debt when the rest of the local authority journey is built next sprint. TODOs have been noted in the code for this to be updated where required.

### Checklist
- [ ] Work items have been linked [(use AB#)](https://learn.microsoft.com/en-us/azure/devops/boards/github/link-to-from-github?view=azure-devops#use-ab-to-link-from-github-to-azure-boards-work-items)
- [ ] Your code builds clean without any errors or warnings
- [ ] You have run all unit/integration tests and they pass
- [ ] Your branch has been rebased onto main
- [ ] You have tested by running locally

2024-05-02 10:53 UTC, jrabbott requested changes

2024-05-02 10:53 UTC, jrabbott commented on web/src/Web.App/Controllers/LocalAuthorityResourcesController.cs
Please remove commented out code

2024-05-02 10:53 UTC, jrabbott commented on web/src/Web.App/Views/LocalAuthorityResources/index.cshtml
Please remove commented out code

2024-05-02 11:29 UTC, J05h-L commented on web/src/Web.App/Controllers/LocalAuthorityResourcesController.cs
removed

2024-05-02 11:29 UTC, J05h-L commented on web/src/Web.App/Views/LocalAuthorityResources/index.cshtml
removed

2024-05-02 12:57 UTC, jrabbott approved these changes

2024-05-02 12:58 UTC, jrabbott commented
@J05h-L assuming tests will be on a separate PR?

2024-05-03 07:03 UTC, J05h-L commented
> @J05h-L assuming tests will be on a separate PR?

Yes will be adding tests separately

2024-05-03 07:03 UTC, merged